
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Hotjar from '@hotjar/browser'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const siteId = 3621680;
const hotjarVersion = 6;



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  Hotjar.init(siteId, hotjarVersion);
  return (
    <html lang="en">
      <body className={inter.className} style={{
        backgroundColor: '#FEFCF6',
        WebkitTapHighlightColor: 'transparent',
      }}>{children}</body>

      
      <script src="//code.tidio.co/hloxn0ikzk1gofdydbknhy8tsaugibff.js" async></script>
      

    </html>
  )
}
